# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
}:
let
  shaMap = {
    i686-linux = "08h6ciqn3sd37yls7hv0341hvd9n3xbd24pk2kzmr6q49hwrflrz";
    x86_64-linux = "05ndjyf8w15cp2ixqi4i42mplmpbjldybm1n7i0dpy8q8rziscd9";
    armv6l-linux = "00fvf0dy30n0nyrh17d04m0l28hblnw6gshkyl0mgqr94sqgq7sa";
    aarch64-linux = "105n5lzrqhzhrhqv7k46hx0jxrhg2hg9ka3pxxhlas534zac2igm";
    x86_64-darwin = "067d2787r5qw1lx9varinmnwv2kf1yd6ql0imjwb30xnnf3c800h";
    aarch64-darwin = "067d2787r5qw1lx9varinmnwv2kf1yd6ql0imjwb30xnnf3c800h";
  };

  urlMap = {
    i686-linux = "https://git.froth.zone/sam/awl/releases/download/v0.6.12/awl_Linux_i386.tar.gz";
    x86_64-linux = "https://git.froth.zone/sam/awl/releases/download/v0.6.12/awl_Linux_amd64.tar.gz";
    armv6l-linux = "https://git.froth.zone/sam/awl/releases/download/v0.6.12/awl_Linux_arm.tar.gz";
    aarch64-linux = "https://git.froth.zone/sam/awl/releases/download/v0.6.12/awl_Linux_arm64.tar.gz";
    x86_64-darwin = "https://git.froth.zone/sam/awl/releases/download/v0.6.12/awl_MacOS_all.tar.gz";
    aarch64-darwin = "https://git.froth.zone/sam/awl/releases/download/v0.6.12/awl_MacOS_all.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "awl";
  version = "0.6.12";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./awl $out/bin/awl
    installManPage ./docs/awl.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "A DNS query client";
    homepage = "https://dns.froth.zone/awl";
    license = lib.licenses.bsd3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
