# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
}:
let
  shaMap = {
    i686-linux = "0ap6flinnqp8yd5w7g6pzpad4zq0k2f95hi9s8gjsj55rc1h2sma";
    x86_64-linux = "17m1miy61lhqndw99hl1linjamk6m7i2mi0lfd30d07lrxqh00c5";
    armv6l-linux = "1j9lshm71xwr67smyn1yw52v4qkb8zi764f1i0iib6krr08m9i4b";
    aarch64-linux = "1pap7dvns61gxrkm0hcqj7zf5pr6lyx4mwwlbwd18w14xgikb3ak";
    x86_64-darwin = "1iv1v2jsfnz99hc1fcclgnzx66iy80j7m9pn7wimcsyy4rfp9yf0";
    aarch64-darwin = "1iv1v2jsfnz99hc1fcclgnzx66iy80j7m9pn7wimcsyy4rfp9yf0";
  };

  urlMap = {
    i686-linux = "https://git.froth.zone/sam/awl/releases/download/v0.6.11/awl_Linux_i386.tar.gz";
    x86_64-linux = "https://git.froth.zone/sam/awl/releases/download/v0.6.11/awl_Linux_amd64.tar.gz";
    armv6l-linux = "https://git.froth.zone/sam/awl/releases/download/v0.6.11/awl_Linux_arm.tar.gz";
    aarch64-linux = "https://git.froth.zone/sam/awl/releases/download/v0.6.11/awl_Linux_arm64.tar.gz";
    x86_64-darwin = "https://git.froth.zone/sam/awl/releases/download/v0.6.11/awl_MacOS_all.tar.gz";
    aarch64-darwin = "https://git.froth.zone/sam/awl/releases/download/v0.6.11/awl_MacOS_all.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "awl";
  version = "0.6.11";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./awl $out/bin/awl
    installManPage ./doc/awl.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "A DNS query client";
    homepage = "https://dns.froth.zone/awl";
    license = lib.licenses.bsd3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
